language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - composer self-update
  - composer --version
  - php --version
  - composer install --prefer-source --no-interaction --dev